apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: default
  # namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: web
      # istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: ""
            # name: inbound|http|8080
            # route:
              # action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: "user-agent"
                  descriptor_key: "USER_AGENT"