apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: USER_AGENT
        value: "moetomato"
        rate_limit:
          unit: minute
          requests_per_unit: 5
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 5